CREATE TABLE IF NOT EXISTS demo_items (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'active',
  note TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO demo_items (name, status, note)
SELECT 'Alpha MySQL', 'active', 'mysql demo item'
WHERE NOT EXISTS (SELECT 1 FROM demo_items WHERE name = 'Alpha MySQL');
