use crate::model::{AppInfo, DataSource};
use crate::schema::{ColumnInfo, TableSchema};
use anyhow::{Context, anyhow};
use reqwest::multipart;
use serde::de::DeserializeOwned;
use serde_json::json;
use std::path::Path;

#[derive(Clone)]
pub struct DbapiClient {
    base_url: String,
    http: reqwest::Client,
}

impl DbapiClient {
    pub fn new(base_url: impl Into<String>) -> anyhow::Result<Self> {
        let base_url = base_url.into().trim().trim_end_matches('/').to_string();
        if base_url.is_empty() {
            anyhow::bail!("base_url is required");
        }
        Ok(Self {
            base_url,
            http: reqwest::Client::new(),
        })
    }

    pub fn url(&self, path: &str) -> String {
        format!("{}/{}", self.base_url, path.trim_start_matches('/'))
    }

    pub async fn list_datasources(&self) -> anyhow::Result<Vec<DataSource>> {
        self.post_json("/datasource/getAll", &json!({})).await
    }

    pub async fn inspect_table_schema(
        &self,
        datasource_id: &str,
        table: &str,
    ) -> anyhow::Result<TableSchema> {
        let columns: Vec<ColumnInfo> = self
            .post_json(
                "/table/getAllColumns",
                &json!({"datasourceId": datasource_id, "table": table}),
            )
            .await?;
        Ok(TableSchema {
            table: table.to_string(),
            columns,
        })
    }

    pub async fn import_groups_file(&self, path: &Path) -> anyhow::Result<()> {
        self.upload_file("/apiConfig/importGroup", path).await
    }

    pub async fn import_api_file(&self, path: &Path) -> anyhow::Result<()> {
        self.upload_file("/apiConfig/import", path).await
    }

    pub async fn create_app_token_for_group(
        &self,
        app_name: &str,
        group_id: &str,
    ) -> anyhow::Result<serde_json::Value> {
        let app: AppInfo = self
            .post_json(
                "/app/create",
                &json!({
                    "name": app_name,
                    "note": "Generated by DBAPI bundle workflow",
                    "expireDesc": "forever"
                }),
            )
            .await?;
        let app_id = app
            .id
            .as_deref()
            .ok_or_else(|| anyhow!("app id missing from /app/create response"))?;
        let secret = app
            .secret
            .as_deref()
            .ok_or_else(|| anyhow!("app secret missing from /app/create response"))?;
        let _: serde_json::Value = self
            .post_json("/app/auth", &json!({"appId": app_id, "groupIds": group_id}))
            .await?;
        self.get_json(&format!("/token/generate?appid={app_id}&secret={secret}"))
            .await
    }

    async fn post_json<T: DeserializeOwned>(
        &self,
        path: &str,
        body: &serde_json::Value,
    ) -> anyhow::Result<T> {
        let response = self
            .http
            .post(self.url(path))
            .json(body)
            .send()
            .await
            .with_context(|| format!("failed to send POST request to {path}"))?;
        parse_response(path, response).await
    }

    async fn get_json<T: DeserializeOwned>(&self, path: &str) -> anyhow::Result<T> {
        let response = self
            .http
            .get(self.url(path))
            .send()
            .await
            .with_context(|| format!("failed to send GET request to {path}"))?;
        parse_response(path, response).await
    }

    async fn upload_file(&self, path: &str, file_path: &Path) -> anyhow::Result<()> {
        let bytes = tokio::fs::read(file_path)
            .await
            .with_context(|| format!("failed to read file {}", file_path.display()))?;
        let filename = file_path
            .file_name()
            .and_then(|value| value.to_str())
            .unwrap_or("bundle.json")
            .to_string();
        let part = multipart::Part::bytes(bytes).file_name(filename);
        let form = multipart::Form::new().part("file", part);
        let response = self
            .http
            .post(self.url(path))
            .multipart(form)
            .send()
            .await
            .with_context(|| format!("failed to upload file to {path}"))?;
        let _: serde_json::Value = parse_response(path, response).await?;
        Ok(())
    }
}

async fn parse_response<T: DeserializeOwned>(
    path: &str,
    response: reqwest::Response,
) -> anyhow::Result<T> {
    let status = response.status();
    let body = response
        .text()
        .await
        .with_context(|| format!("failed to read response body from {path} ({status})"))?;
    if !status.is_success() {
        anyhow::bail!("request to {path} failed with status {status}: {body}");
    }

    let value: serde_json::Value = serde_json::from_str(&body)
        .with_context(|| format!("failed to parse JSON response from {path} ({status}): {body}"))?;
    if let Some(success) = value.get("success").and_then(serde_json::Value::as_bool) {
        let message = value
            .get("msg")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("DBAPI request failed");
        if !success {
            anyhow::bail!("request to {path} failed with status {status}: {message}; body: {body}");
        }
        let data = value
            .get("data")
            .cloned()
            .unwrap_or(serde_json::Value::Null);
        return serde_json::from_value(data).with_context(|| {
            format!("failed to decode DBAPI data from {path} ({status}): {body}")
        });
    }

    serde_json::from_value(value)
        .with_context(|| format!("failed to decode response from {path} ({status}): {body}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn joins_base_url_and_path() {
        let client = DbapiClient::new("http://127.0.0.1:8520/").unwrap();
        assert_eq!(
            client.url("/datasource/getAll"),
            "http://127.0.0.1:8520/datasource/getAll"
        );
    }

    #[test]
    fn rejects_empty_base_url() {
        assert!(DbapiClient::new("  ").is_err());
    }
}
